server:
#  port: 8081
  error:
    include-stacktrace: always
    include-exception: true

#omise co
omise:
  public-key: pkey_test_5x9z9ovaogftf7hp4nf
  secret-key: skey_test_5xa1l9s31xhmncsoq1d

management:
  endpoints:
    web:
      exposure:
        include: "*"


logging:
  level:
    org.axonframework:
              extensions:
                kafka:
                  eventhandling:
                      tokenstore.TokenStoreState: INFO
    org.springframework.data.redis: DEBUG
    com:
      squareup.okhttp3: DEBUG
      splunk.logging: DEBUG
      github:
        benmanes:
                  caffeine: DEBUG
    org.springdoc: DEBUG
    kafka: DEBUG
    reactor:
      core:
        publisher: DEBUG
#    org:
#      hibernate:
#          SQL: DEBUG
#          type:
#            descriptor:
#              sql: TRACE
      springframework:
                cloud.stream:
                        binder: DEBUG
                        binder.kafka: DEBUG
                security: DEBUG
                web: DEBUG
                cache: DEBUG

#                mail: DEBUG
#      hibernate: DEBUG


#java mail properties
#spring:
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: cheongkarwai5@gmail.com
#    password: lnmq wuql snfq yvis
#    properties:
#      mail:
#        debug: true
#        smtp:
#          auth: true
#          starttls:
#              enable: true
axoniq:
  console:
    application-name: E-Commerce
    credentials: 98f81701-0:40393ee520864d15828837ff592c9193
    dlq-mode: FULL
spring:
  #  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com
#          issuer-uri: https://securetoken.google.com/spring-boot-auth-service
  profiles:
    active: dev
  session:
    timeout: 10m
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_URL}
      default-binder: reactorKafka
      bindings:
        productInput-in-0:
          destination: product
          content-type: application/json
  application:
    name: test
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: test
  kafka:
    consumer:
      enable-auto-commit: false
      auto-offset-reset: earliest
      bootstrap-servers: ${KAFKA_URL}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: ${KAFKA_URL}

springdoc:
  enable-hateoas: false
axon:
  eventhandling:
    processors:
      product:
        mode: tracking
  axonserver:
    servers: localhost:8124
  kafka:
    bootstrap-servers: ${KAFKA_URL}
    client-id: kafka-axon-example
    default-topic: axon-events
    properties:
      security.protocol: PLAINTEXT

    publisher:
      confirmation-mode: transactional

    producer:
      transaction-id-prefix: kafka-sample
      retries: 3
      event-processor-mode: subscribing
    # For additional unnamed properties, add them to the `properties` map like so
      properties:
        enable.idempotence: true

    fetcher:
      poll-timeout: 3000

    consumer:
      enable-auto-commit: true
      auto-commit-interval: 3000
      event-processor-mode: tracking
    # For additional unnamed properties, add them to the `properties` map like so
#      properties:
#        some-key: [some-value]

