services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    ports:
      - "8080:8080"
    environment:
      KC_DB_URL_HOST: 192.168.0.233 # Accesses the host Postgres
      KC_DB_URL_PORT: 5432
      KC_DB: postgres
     # KC_DB_URL: jdbc:postgresql://localhost:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: root
      KC_DB_URL_DATABASE: keycloak

      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
    command:
      - start-dev